#### 9/06/2023 {#white}

[**Easton White, Ph.D.**\
Assistant Professor, Biological Sciences\
University of New Hampshire](https://quantmarineecolab.github.io/)

#### ***Socio-ecological dynamics of fisheries in the face of extreme events***

Extreme events are, by definition, rare, but they can have significant consequences for systems. This is especially the case in socio-ecological systems that involve linkages between several-subsystems, allowing to the effects of an extreme event to propagate. In this talk, I'll highlight studies focused on how extreme events affect the socio-ecological dynamics of fisheries. The talk will contain case studies on coral reef fisheries, COVID-19 and seafood, and recreational fisheries. I'll show that shock events can dramatically alter the course of the socio-ecological system and change management recommendations. I identify counter-intuitive situations where the degradation of habitat via a shock event can help the system persist in a healthy state as a result of feedback from the social dynamics.

Dr. Easton White is a quantitative marine ecologist who uses mathematical and statistical tools, coupled with experiments and field observations, to answer questions in ecology, conservation science, sustainability, and ecosystem management. Most of his work is focused on marine systems, especially fisheries and spatial planning. Easton currently conducts research on assessing the effectiveness of protected area networks, improving species monitoring programs, and modeling socio-ecological systems in the context of fisheries. His work centers on how environmental variability, in particular rare events (e.g., hurricanes, COVID-19 pandemic), affects ecosystems and those that depend on them. He is currently recruiting for graduate students within the Quantitative Marine Ecology Lab at the University of New Hampshire working with Professor Easton White. Please see here ([https://quantmarineecolab.github.io/join/](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fquantmarineecolab.github.io%2Fjoin%2F&data=05%7C01%7Cgfay%40umassd.edu%7C2f1b6dbd36c648e43a5708db935fefc0%7C328d6c0d0f2f4b7693109762ba1c3e2d%7C0%7C0%7C638265812886395101%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3WF%2FQiYAemE2d9Fo%2FZJph3xbRTip4AcJH0%2B9TqNMcSI%3D&reserved=0 "Original URL: https://quantmarineecolab.github.io/join/. Click or tap if you trust this link.")) for more information on how to apply.

------------------------------------------------------------------------

#### 9/13/2023 {#bachman}

[**Michelle Bachman**\
Fishery Analyst, Habitat Plan Coordinator\
New England Fishery Management Council](nefmc.org)

#### ***Area-Based Management at the Regional Fishery Management Councils***

Conservation areas are one of many tools to manage fisheries and conserve ecosystems and associated biodiversity in U.S. marine waters. Working under the direction of the Council Coordination Committee, the Area-Based Management Subcommittee developed a project-specific definition of 'conservation' and identified 648 areas in three categories, ecosystem conservation, year-round fishery management, and seasonal / other areas. In total, these areas currently cover 72% of the total U.S. Exclusive Economic Zone (EEZ).

A substantial proportion of the U.S. EEZ is conserved relative to environmentally adverse fishing activities. Year-round, bottom trawling is prohibited in 56% of the EEZ, and all bottom tending gear (including trawls, dredges, bottom longlines, and pots) in 37%. These area-based gear restrictions complement other management tools used by the Councils to ensure sustainable fisheries and ecosystems, such as conservative catch limits, bycatch limits on non-target species, and limitations on legal gears. Collectively, these measures meet objectives and national standards that ensure the maintenance of biological productivity and biodiversity, while affording access to nature through recreational opportunities and healthy, sustainable seafood for consumers.

Our conservation areas database has been shared with NOAA Fisheries to support the Administration's efforts to compile an America the Beautiful (ATB) Conservation Atlas. The Administration's area-based conservation goal of 30% of U.S. lands and waters by 2030 is framed as an important part of our nation's solution to the climate crisis. Many authors have discussed the contribution that area-based management makes to promoting climate resilience in marine ecosystems. The answer to whether fisheries management areas are similarly effective to fully protected marine reserves, or if they promote ecosystem resilience to climate change, appears to be 'it depends'. By contributing our detailed accounting of fisheries conservation areas to the broader ATB inventory, the Councils endeavor to support development of a robust conservation atlas that fully reflects the contribution of fishery management areas to 30/30 objectives.

Michelle Bachman has worked as an analyst with the New England Fishery Management Council since December 2008. She supports the Council's habitat-related initiatives, chairing the Habitat Plan Development Team since 2009. She served as the staff lead for the Council's Essential Fish Habitat Amendment 2, Deep-Sea Coral Amendment, Clam Dredge Exemption Framework, Atlantic Salmon Aquaculture Framework, Southern New England Habitat Area of Particular Concern Framework, and currently, is co-lead on the Northern Edge Habitat-Scallop Framework. Broadly, these actions relate to minimization of fishing effects on marine habitats. She helps the Council stay connected to and comment on offshore wind, habitat mapping, and marine spatial planning issues, with a particular focus on non-fishing activities that might affect fishery species and their habitats. Ms. Bachman represents the Council on numerous external committees, including the Council Coordination Committee Area-Based Management Sub-Committee and Habitat Work Group, the East Coast Climate Change Scenario Planning Core Team, the Hudson Canyon National Marine Sanctuary Advisory Council, the Atlantic States Marine

Fisheries Commission Habitat Committee, and the Responsible Offshore Science Alliance Advisory Council. Ms. Bachman studied biology and environmental studies at Tufts University and received her M.S. degree in Living Marine Resource Science and Management from the University of Massachusetts Dartmouth School for Marine Science and Technology in 2009.

------------------------------------------------------------------------

#### 9/20/2023 {#kahl}

[**Katherine Kahl, Ph.D.**\
Extension Assistant Professor, Coastal Resilience & Sustainable Fisheries\
University of Massachusetts Amherst](https://eco.umass.edu/people/faculty/kahl-katherine/)

#### *UMass Amherst Gloucester Marine Station: Our vision forward*

------------------------------------------------------------------------

#### 9/27/2023 {#caracappa}

[Joseph Caracappa, Ph.D.\
Ecosystem Modeler\
NOAA Fisheries Northeast Fisheries Science Center](https://www.fisheries.noaa.gov/contact/joseph-caracappa)

#### *Building a Climate-Ready Northeast U.S. Atlantis Ecosystem Model*

With increased concern on the impacts of climate change on the northeast U.S., there is a growing need for modelling products that can relate large-scale environmental change to regional and local processes. End-to-end ecosystem models, like Atlantis, simulate ecosystem-wide processes from physics and biogeochemistry, to ecological processes and population dynamics, all through socioeconomic impacts. The Northeast U.S. Atlantis ecosystem model (NEUSv2) is such a model, and while much of its development has focused on its ability to reproduce critical ecosystem processes and validated against data, it's not yet "climate-ready". This talk will discuss the development workflow and modeling efforts of NEUSv2, some broader observations on the tradeoffs between model skill, complexity, and resources, as well as some current work to improve NEUSv2's ability to relate global climate change to regional/local impacts.

Dr. Joe Caracappa is a life-long resident of the northeast U.S. After growing up in rural NH, he received his undergraduate at Boston College. Later he received his PhD at Rutgers University studying the effects of larval morphology and behavior on population connectivity and dispersal. Joe then worked as a post-doctoral researcher with the National Research Council at NOAA's Northeast Fisheries Science Center to work on the development of its regional Atlantis ecosystem model. He has now continued as a contractor at the NEFSC working towards the operationalization of the NEUSv2 Atlantis model.

------------------------------------------------------------------------

#### 10/04/2023 {#dolan}

[**Tara Dolan, Ph.D.**\
Research fisheries biologist\
Massachusetts Division of Marine Fisheries](https://scholar.google.com/citations?user=Xndpi9YAAAAJ&hl=en)

#### *Exploring population connectivity in winter flounder*

The expression of alternative life-history strategies can be advantageous for a species that experiences fluctuating environmental conditions. Intra-species differences in migration propensity and the timing of spawning create diverse population components which can respond plastically to environmental variability, promoting long-term stability within the population. However, such intra-specific diversity can also lead to challenges for the assessment and management of harvested species when we can no longer assume that stocks with such diverse subcomponents have homogeneous population dynamics. A concern for the assessment and management of Southern New England/Mid-Atlantic winter flounder (*Pseudopleuronectes americanus*) is whether diversity in migration propensity and the timing and location of spawning results in persistent stock structure. We characterized intra-specific behavioral diversity in migration propensity for winter flounder across multiple spatial scales. The migration propensity and natal origin for individual flounder were cross-referenced with their genotype, allowing us to compare genetic signatures of population structure with migration and spawning behavior. Including the role of behavior in mediating population connectivity will lead to more accurate interpretation of the causes and consequences of changes in fisheries productivity, and thus help us design more accurate assessment and effective management strategies.

------------------------------------------------------------------------

#### 10/11/2023 {#quest}

[**CINAR QUEST Fellows in Quantitative Fishery and Ecosystem Science**](www.cinar.org)

[Gavin Fay, Ph.D.\
Associate Professor, Fisheries Oceanography, University of Massachusetts Dartmouth](www.thefaylab.com)\
[Genevieve Nesslage, Ph.D.\
Associate Research Professor, University of Maryland Center for Environmental Science](https://www.umces.edu/genevieve-nesslage)\
[Joshua Stoll, Ph.D.\
Assistant Professor, University of Maine](https://joshua-stoll.com/)\
[John Wiedenmann, Ph.D.\
Assistant Professor, Ecology, Evolution and Natural Resources, Rutgers University](https://deenr.rutgers.edu/faculty/John_Wiedenmann.html)

------------------------------------------------------------------------

#### 10/18/2023

[**Robert DeConto, Ph.D.o, Ph.D.**\
Provost Professor; Director, School of Earth & Sustainability; Dept. of Earth, Geographic, & Climate Sciences\
University of Massachusetts Amherst](https://blogs.umass.edu/deconto/?_gl=1%2A1lccyo1%2A_gcl_au%2AMTE1NTE1NTQxLjE2ODk2MDk4NTc.%2A_ga%2ANTA0OTQ1NDc4LjE2ODk2MDk4NTc.%2A_ga_21RLS0L7EB%2AMTY5Mjk3Njk5My40LjAuMTY5Mjk3Njk5Ni4wLjAuMA..)

------------------------------------------------------------------------

#### 11/01/2023 {#leonard}

[**Kelsey Leonard, Ph.D.**\
Assistant Professor, Faculty of Environment\
University of Waterloo](https://www.kelseyleonard.com/)

------------------------------------------------------------------------

#### 11/08/2023 {#mills}

[**Katherine Mills, Ph.D.**\
Research Scientist\
Gulf of Maine Research Institute](https://gmri.org/our-approach/staff/kathy-mills/)

#### *Climate Impacts and Resilience in Marine Fisheries*

Climate change is altering oceans and marine ecosystems around the world, pushing physical conditions beyond recent analogues, driving biological changes, and creating impacts that cascade through social-ecological systems. The Northeast U.S. Shelf has experienced rapid warming of ocean temperatures, recurring marine heatwaves, and an exceptionally warm temperature regime over the past decade. Fish and invertebrate populations across the region are being affected in a variety of ways, including changes in distribution, growth, phenology, and productivity. Moreover, changing ocean uses that can support climate adaptation and mitigation are also affecting marine ecosystems and fisheries. The nature of these impacts and ability of fishery stakeholders to respond to them are mediated by the ecological, socio-economic, and governance context within which fisheries operate. This presentation will examine attributes of and pathways to climate resilience in marine fisheries in the Northeast US and relate experiences here to those in fisheries around the world. It will also highlight bidirectional global-local perspectives to identify multifaceted strategies to support climate adaptation and resilience in marine fisheries, including measures directed towards enhancing fish stocks and ecosystem health, reinforcing or building social capacities, expanding economic opportunities, and enhancing governance responsiveness and effectiveness.

Dr. Katherine Mills is a senior research scientist at the Gulf of Maine Research Institute in Portland, Maine. She earned her Ph.D. in Natural Resources at Cornell University. As a quantitative fisheries ecologist, Kathy studies marine ecosystem changes and fish-ecosystem-fishery relationships with a focus on the Gulf of Maine and Northeast US Shelf regions. Specifically, her research investigates (1) how physical and ecosystem conditions are changing; (2) how these changes affect fish populations, biological communities, and marine fisheries; and (3) how fisheries and fishing communities can effectively respond. Much of her work is interdisciplinary and collaborative, working with scientists and stakeholders to understand and inform management of fisheries as coupled social-ecological systems and to support climate adaptation and resilience in marine fisheries. She leads a UN Ocean Decade program---Fisheries Strategies for Changing Oceans and Resilient Ecosystems by 2030 (FishSCORE), is lead author for the \'Ocean Ecosystems and Marine Resources\' chapter of the US 5th National Climate Assessment, and serves as a chair of the ICES-PICES Strategic Initiative on Climate Change Impacts on Marine Ecosystems (SICCME).

------------------------------------------------------------------------

#### 11/15/2023 {#marjadi}

[**Meghna Marjadi, Ph.D.**\
Postdoctoral Research Fellow\
University of Massachusetts Dartmouth](https://www.linkedin.com/in/meghna-n-marjadi-10791332/)

#### *Climate-related impacts on reproductive success and phenological events for anadromous river herring*

------------------------------------------------------------------------

#### 11/29/2023 {#donelan}

[**Sarah Donelan, Ph.D.**\
Assistant Professor, Department of Biology\
University of Massachusetts Dartmouth](https://sarahdonelanphd.weebly.com/)

#### ***Legacies of stress: eco-evolutionary consequences of transgenerational and carryover effects in coastal systems***

Phenotypic plasticity is a critical component of organismal responses to environmental change. My seminar will focus on a central theme of my research program -- "legacy effects," or how past environmental experiences shape organism phenotypes, the mechanisms of these changes, and the consequences of these changes for communities and ecosystems. We will explore how parental experience with predators influences fitness and physiology in intertidal snails and how early life exposure to climate change stressors impacts oyster growth and nitrogen storage, a critical ecosystem service.

Dr. Sarah Donelan's research focuses on how marine organisms respond to stress across generations and life stages. She works primarily with marine invertebrates like snails and oysters found along the coast of Massachusetts and explores stressors that affect many coastal organisms, including those associated with climate change, predation, and species invasions. She began as an Assistant Professor at UMass Dartmouth in Fall 2023. Prior to UMassD, she was a postdoctoral fellow at the Smithsonian Environmental Research Center in Maryland. She received her Ph.D. in Ecology, Evolution, and Marine Biology from Northeastern University and her B.A. in Biology from Wesleyan University. In her downtime, she enjoys spending time outdoors with her husband and infant daughter, cycling, watching Survivor, and tending to her many houseplants.

------------------------------------------------------------------------

#### 12/06/2023 {#cope}

[**Jason Cope, Ph.D.**\
Research Fish Biologist\
NOAA Fisheries Northwest Fisheries Science Center](https://www.fisheries.noaa.gov/contact/jason-cope-phd)

#### ***Tools and principles to support science-based fisheries management across the world***

------------------------------------------------------------------------
